(ns hello-world.names)

(def sample-names [{:name "Alberto" :sex "male" :age 17}
                   {:name "Alice" :sex "female" :age 31}
                   {:name "Amina" :sex "female" :age 19}
                   {:name "Anderson" :sex "male" :age 19}
                   {:name "Arnold" :sex "male" :age 41}
                   {:name "August" :sex "male" :age 8}
                   {:name "Benito" :sex "male" :age 12}
                   {:name "Bob", :sex "male" :age 33}
                   {:name "Brett" :sex "male" :age 20}
                   {:name "Brittni" :sex "female" :age 21}

                   {:name "Carletta" :sex "female" :age 25} ;; 11th...
                   {:name "Carrol" :sex "male" :age 25}
                   {:name "Cedric" :sex "male" :age 25}
                   {:name "Charles" :sex "male" :age 25}
                   {:name "Cheryle" :sex "female" :age 25}
                   {:name "Chet" :sex "male" :age 25}
                   {:name "Chlöe", :sex "female" :age 25}
                   {:name "Christia" :sex "female" :age 25}
                   {:name "Christine", :sex "female" :age 25}
                   {:name "Cristal" :sex "female" :age 25}
                   {:name "Dana" :sex "male" :age 25}
                   {:name "Danial" :sex "male" :age 25}
                   {:name "Dawn" :sex "female" :age 25}
                   {:name "Dessie" :sex "female" :age 25}
                   {:name "Eduardo" :sex "male" :age 25}
                   {:name "Elaine" :sex "female" :age 25}
                   {:name "Emanuel" :sex "male" :age 25}
                   {:name "Emery" :sex "male" :age 25}
                   {:name "Emily" :sex "female" :age 25}
                   {:name "Ethel" :sex "female" :age 25}
                   {:name "Everett" :sex "male" :age 25}
                   {:name "Evon" :sex "female" :age 25}
                   {:name "Fabian" :sex "male" :age 25}
                   {:name "Fausto" :sex "male" :age 25}
                   {:name "Federico" :sex "male" :age 25}
                   {:name "Felix" :sex "male" :age 25}
                   {:name "Fernanda" :sex "female" :age 25}
                   {:name "Ferne" :sex "female" :age 25}
                   {:name "Fidel" :sex "male" :age 25}
                   {:name "Florentino" :sex "male" :age 25}
                   {:name "Fred", :sex "male" :age 25}
                   {:name "Fredric" :sex "male" :age 25}
                   {:name "Gordon" :sex "male" :age 25}
                   {:name "Greg" :sex "male" :age 25}
                   {:name "Gwen" :sex "female" :age 25}
                   {:name "Hans" :sex "male" :age 25}
                   {:name "Helen", :sex "female" :age 25}
                   {:name "Hiram" :sex "male" :age 25}
                   {:name "Hugo" :sex "male" :age 25}
                   {:name "Ivan", :age 19 :sex "male"}
                   {:name "Jack", :sex "male" :age 25}
                   {:name "Jackson" :sex "male" :age 25}
                   {:name "Jacquelyne" :sex "female" :age 25}
                   {:name "James", :sex "male" :age 25}
                   {:name "Jeanmarie" :sex "female" :age 25}
                   {:name "Jill", :sex "female" :age 25}
                   {:name "Joanne" :sex "female" :age 25}
                   {:name "Jodi" :sex "female" :age 25}
                   {:name "John", :sex "male" :age 25}
                   {:name "Jonathon" :sex "male" :age 25}
                   {:name "Julio" :sex "male" :age 25}
                   {:name "Justina" :sex "female" :age 25}
                   {:name "Katerina", :sex "female" :age 25}
                   {:name "Lamar" :sex "male" :age 25}
                   {:name "Larae" :sex "female" :age 25}
                   {:name "Lela" :sex "female" :age 25}
                   {:name "Leo", :sex "male" :age 25}
                   {:name "Leonora" :sex "female" :age 25}
                   {:name "Lesley" :sex "male" :age 25}
                   {:name "Lidia" :sex "female" :age 25}
                   {:name "Lien" :sex "female" :age 25}
                   {:name "Lise" :sex "female" :age 25}
                   {:name "Lonnie" :sex "male" :age 25}
                   {:name "Lorenzo" :sex "male" :age 25}
                   {:name "Lorriane" :sex "female" :age 25}
                   {:name "Luana" :sex "female" :age 25}
                   {:name "Lucas" :sex "male" :age 25}
                   {:name "Ma" :sex "female" :age 25}
                   {:name "Major" :sex "male" :age 25}
                   {:name "Margit" :sex "female" :age 25}
                   {:name "Margret" :sex "female" :age 25}
                   {:name "Mariam" :sex "female" :age 25}
                   {:name "Marlo" :sex "female" :age 25}
                   {:name "Melany" :sex "female" :age 25}
                   {:name "Meridith" :sex "female" :age 25}
                   {:name "Micheal" :sex "male" :age 25}
                   {:name "Mohamed" :sex "male" :age 25}
                   {:name "Nydia" :sex "female" :age 25}
                   {:name "Paul" :sex "male" :age 25}
                   {:name "Peter" :sex "male" :age 25}
                   {:name "Raleigh" :sex "male" :age 25}
                   {:name "Renaldo" :sex "male" :age 25}
                   {:name "Rochelle" :sex "female" :age 25}
                   {:name "Romeo" :sex "male" :age 25}
                   {:name "Ruthe" :sex "female" :age 25}
                   {:name "Samantha", :sex "female" :age 25}
                   {:name "Sebrina" :sex "female" :age 25}
                   {:name "Shala" :sex "female" :age 25}
                   {:name "Shannon" :sex "male" :age 25}
                   {:name "Sharolyn" :sex "female" :age 25}
                   {:name "Sherrell" :sex "female" :age 25}
                   {:name "Sherrill" :sex "female" :age 25}
                   {:name "Sondra" :sex "female" :age 25}
                   {:name "Susan", :sex "female" :age 25}
                   {:name "Tandra" :sex "female" :age 25}
                   {:name "Tarah" :sex "female" :age 25}
                   {:name "Tarsha" :sex "female" :age 25}
                   {:name "Tequila" :sex "female" :age 25}
                   {:name "Tessie" :sex "female" :age 25}
                   {:name "Trey" :sex "male" :age 25}
                   {:name "Ulysses" :sex "male" :age 25}
                   {:name "Vern" :sex "male" :age 25}
                   {:name "Warner" :sex "male" :age 25}
                   {:name "Wilber" :sex "male" :age 25}])
